### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by thisisaaronland** [openvenues/lieu#7]
```
/usr/local/bin/dedupe_geojson -o . /usr/local/data/lieu/whosonfirst-data-venue-us-ny.txt
...
did 161260000 hashes requiring 17220432 pairwise comparisons
did 161270000 hashes requiring 17220621 pairwise comparisons
Traceback (most recent call last):
  File "/usr/local/bin/dedupe_geojson", line 420, in <module>
    is_dupe = dupe_func(canonical, other, dupe_pairs, dupes, **dupe_func_kw)
  File "/usr/local/bin/dedupe_geojson", line 113, in is_name_address_dupe
    fuzzy_street_name=fuzzy_street_names)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 388, in dupe_class_and_sim
    same_address = cls.is_address_dupe(a1, a2, languages=languages, fuzzy_street_name=fuzzy_street_name)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 126, in is_address_dupe
    dupe_class, sim = cls.address_dupe_status(a1, a2, languages=languages, fuzzy_street_name=fuzzy_street_name)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 45, in address_dupe_status
    a2_house_number = a2_house_number.strip()
AttributeError: 'int' object has no attribute 'strip'
```

Input file prepared as follows:

```
# https://github.com/whosonfirst/go-whosonfirst-lieu/blob/master/cmd/lieu-prepare-wof.go
./bin/lieu-prepare-wof -out /usr/local/data/lieu/whosonfirst-data-venue-us-ny.txt /usr/local/data/whosonfirst-data-venue-us-ny
```

**Comment by albarrentine** [comment]
That would mean it's an integer in the GeoJSON, and all of the address fields in lieu are expected to be strings (we'd decided to do minimal input sanitization in this library and leave that to the user). Libpostal's parser returns strings, so assuming the house number in that case was already split out in the original. In any case, added a cast on the lieu side with https://github.com/openvenues/lieu/commit/a343d702e2eb2e54a9b6a28606f33f208c5c93d2

**Comment by thisisaaronland** [comment]
The problem was appears to have been `0.0, 0.0` coords. I removed all the records visiting Null Island and the deduping process worked as expected.

I have added tests and enstringification code here, but let me know if I'm missing anything or if my assumptions are incorrect:

https://github.com/whosonfirst/go-whosonfirst-lieu/blob/master/lieu.go

A non-urgent feature request for the code would be informative error messages when the user (me...) passes in bunk data but I am aware that "clean data" was taken as a given for version 1 :-)
